FROM golang

LABEL service="gateway"

ENV SERVICE_NAME="Gateway" \
    SERVICE_VERSION="1.0" \
    SERVICE_PORT="8080" \
    CONSUL_ADDRESS="consul:8500" \
    RABBITMQ_ADDRESS="amqp://rabbitmq:5672" \
    INFLUXDB_ADDRESS="http://influxdb:8086" \
    INFLUXDB_DATABASE="Test"

ADD . /go/src/github.com/gkarlik/quark

WORKDIR /go/src/github.com/gkarlik/quark

# install dependencies
RUN go get google.golang.org/grpc
RUN go get github.com/gorilla/mux

# install govendor
RUN go get -u github.com/kardianos/govendor

# synchronize dependencies
RUN govendor sync

WORKDIR /go/src/github.com/gkarlik/quark/examples/complete/gateway

# build sum service
RUN go build -o /go/bin/gateway main.go

WORKDIR /go/bin

ENTRYPOINT gateway

EXPOSE 8080:8080