version: '2'

services:    
    service:
        build:
            context: .
            dockerfile: Dockerfile-service
        depends_on:
            - consul
            - rabbitmq

    consul:
        image: consul
    
    rabbitmq:
        image: rabbitmq:3.6.5-management
    
