FROM golang

LABEL service="sum"

ENV SERVICE_NAME="Sum Service" \
    SERVICE_VERSION="1.0" \
    SERVICE_PORT="9999" \
    CONSUL_ADDRESS="consul:8500" \
    RABBITMQ_ADDRESS="amqp://rabbitmq:5672" \
    INFLUXDB_ADDRESS="http://influxdb:8086" \
    INFLUXDB_DATABASE="Test"

ADD . /go/src/github.com/gkarlik/quark

WORKDIR /go/src/github.com/gkarlik/quark

# install dependencies
RUN go get google.golang.org/grpc

# install govendor
RUN go get -u github.com/kardianos/govendor

# synchronize dependencies
RUN govendor sync

WORKDIR /go/src/github.com/gkarlik/quark/examples/complete/service

# build sum service
RUN go build -o /go/bin/sum_service main.go

WORKDIR /go/bin

ENTRYPOINT sum_service

EXPOSE 9999:9999