version: '2'

services:    
    service:
        build:
            context: .
            dockerfile: Dockerfile-service
        depends_on:
            - consul
            - rabbitmq

    gateway:
        build:
            context: .
            dockerfile: Dockerfile-gateway
        depends_on:
            - service
            - consul
            - rabbitmq

    consul:
        image: consul
    
    rabbitmq:
        image: rabbitmq:3.6.5-management

    influxdb:
        image: influxdb
    
